library(signifinder)
library(testthat)
suppressPackageStartupMessages(library(SummarizedExperiment))

test_that("EMTSign based on Miow's work", {
    pyrnames <- c("Epithelial", "Mesenchymal")
    pname <- sample(pyrnames, 1)
    rmatrix <- fakeData(pname)
    myres <- EMTSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true(pname %in% colnames(colData(myres)))
    expect_length(colData(myres)[,pname], ncol(assay(myres)))
    expect_type(colData(myres)[,pname], "double")
    expect_message(EMTSign(rmatrix), "100")
})

test_that("EMTSign based on Mak's work", {
    rmatrix  <- fakeData("EMT_Mak")
    myresMak <- EMTSign(rmatrix, author = "Mak")
    expect_true(is(myresMak, "SummarizedExperiment"))
    expect_true("EMT_Mak" %in% colnames(colData(myresMak)))
    expect_length(colData(myresMak)[,"EMT_Mak"], ncol(assay(myresMak)))
    expect_type(colData(myresMak)[,"EMT_Mak"], "double")
    expect_message(EMTSign(rmatrix, author = "Mak"), "100")
})

test_that("EMTSign based on Cheng's work", {
    rmatrix  <- fakeData("EMT_Cheng")
    myres <- EMTSign(rmatrix, author = "Cheng")
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("EMT_Cheng" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"EMT_Cheng"], ncol(assay(myres)))
    expect_type(colData(myres)[,"EMT_Cheng"], "double")
    expect_message(EMTSign(rmatrix, author = "Cheng"), "100")
})

test_that("platinumResistanceSign work", {
    pyrnames <- c("PlatinumResistanceUp", "PlatinumResistanceDown")
    pname <- sample(pyrnames, 1)
    rmatrix <- signifinder:::fakeData(pname)
    myres <- platinumResistanceSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true(pname %in% colnames(colData(myres)))
    expect_length(colData(myres)[,pname], ncol(assay(myres)))
    expect_type(colData(myres)[,pname], "double")
    expect_message(platinumResistanceSign(rmatrix), "100")
})

test_that("ASCSign work", {
    rmatrix  <- signifinder:::fakeData("ASC")
    myres <- ASCSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("ASC" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"ASC"], ncol(assay(myres)))
    expect_type(colData(myres)[,"ASC"], "double")
    expect_message(ASCSign(rmatrix), "100")
})

test_that("chemokineSign work", {
    rmatrix  <- fakeData("Chemokines_Messina")
    myres <- chemokineSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("Chemokines_Messina" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"Chemokines_Messina"], ncol(assay(myres)))
    expect_type(colData(myres)[,"Chemokines_Messina"], "double")
    expect_message(chemokineSign(rmatrix), "100")
})

test_that("PassONSign work", {
    rmatrix  <- signifinder:::fakeData("PASS.ON")
    myres <- PassONSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("PASS.ON" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"PASS.ON"], ncol(assay(myres)))
    expect_type(colData(myres)[,"PASS.ON"], "double")
    expect_message(PassONSign(rmatrix), "100")
})


test_that("CISSign work", {
    pyrnames <- c("CISup", "CISdown")
    pname <- sample(pyrnames, 1)
    rmatrix  <- signifinder:::fakeData(pname)
    myres <- CISSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    pname <- substring(pname, 1,3)
    expect_true(pname %in% colnames(colData(myres)))
    expect_length(colData(myres)[,pname], ncol(assay(myres)))
    expect_type(colData(myres)[,pname], "double")
    expect_message(CISSign(rmatrix), "100")
})

test_that("HRDSSign work", {
    rmatrix  <- signifinder:::fakeData("HRDS")
    myres <- HRDSSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("HRDS" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"HRDS"], ncol(assay(myres)))
    expect_type(colData(myres)[,"HRDS"], "double")
    expect_message(HRDSSign(rmatrix), "100")
})

test_that("DNArepSign work", {
    rmatrix  <- signifinder:::fakeData("DNArepair")
    myres <- DNArepSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("DNArepair" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"DNArepair"], ncol(assay(myres)))
    expect_type(colData(myres)[,"DNArepair"], "integer")
    expect_message(DNArepSign(rmatrix), "100")
})

# test_that("IPRES work", {
#     rmatrix  <- fakeData("IPRES")
#     myres <- IPRESSign(rmatrix)
#     expect_true(is(myres, "SummarizedExperiment"))
#     expect_true("IPRES" %in% colnames(colData(myres)))
#     expect_length(colData(myres)[,"IPRES"], ncol(assay(myres)))
#     expect_type(colData(myres)[,"IPRES"], "double")
#     expect_message(IPRESSign(datasetm), "100")
# })
