library(signifinder)
library(SummarizedExperiment)
library(labstatR)

test_that("TLSSign works", {
    rmatrix <- fakeData("TLS")
    myres <- TLSSign(rmatrix, nametype = "SYMBOL", tumorTissue = "skin")
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("TLS" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"TLS"], ncol(assay(myres)))
    expect_type(colData(myres)[,"TLS"], "double")
    myoutput <- capture.output(TLSSign(rmatrix, nametype = "SYMBOL", tumorTissue = "skin"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})

test_that("ExpandedImmuneSign works", {
    rmatrix <- fakeData("ExpandedImmune")
    myres <- expandedImmuneSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("ExpandedImmune" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"ExpandedImmune"], ncol(assay(myres)))
    expect_type(colData(myres)[,"ExpandedImmune"], "double")
    myoutput <- capture.output(expandedImmuneSign(rmatrix, nametype = "SYMBOL", tumorTissue = "pan-tissue"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})

test_that("IFNSign works", {
    rmatrix <- fakeData("IFN")
    myres <- IFNSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("IFN" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"IFN"], ncol(assay(myres)))
    expect_type(colData(myres)[,"IFN"], "double")
    myoutput <- capture.output(IFNSign(rmatrix, nametype = "SYMBOL", tumorTissue = "pan-tissue"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})

test_that("CYTSign works", {
    rmatrix <- fakeData("CYT")
    myres <- CYTSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("CYT" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"CYT"], ncol(assay(myres)))
    expect_type(colData(myres)[,"CYT"], "double")
    myoutput <- capture.output(CYTSign(rmatrix, nametype = "SYMBOL", tumorTissue = "pan-tissue"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})

test_that("MitoticIndexSign works", {
    rmatrix <- fakeData("MitoticIndex")
    myres <- mitoticIndexSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("MitoticIndex" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"MitoticIndex"], ncol(assay(myres)))
    expect_type(colData(myres)[,"MitoticIndex"], "double")
    myoutput <- capture.output(mitoticIndexSign(rmatrix, nametype = "SYMBOL", tumorTissue = "pan-tissue"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})

test_that("MatrisomeSign works", {
    rmatrix <- fakeData("Matrisome")
    myres <- matrisomeSign(rmatrix)
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("Matrisome" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"Matrisome"], ncol(assay(myres)))
    expect_type(colData(myres)[,"Matrisome"], "integer")
    myoutput <- capture.output(matrisomeSign(rmatrix, nametype = "SYMBOL", tumorTissue = "pan-tissue"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})

test_that("immunoScoreSign works", {
    rmatrix <- fakeData("ImmunoScoreRoh")
    myres <- immunoScoreSign(rmatrix, author = "Roh")
    expect_true(is(myres, "SummarizedExperiment"))
    expect_true("ImmunoScoreRoh" %in% colnames(colData(myres)))
    expect_length(colData(myres)[,"ImmunoScoreRoh"], ncol(assay(myres)))
    expect_type(colData(myres)[,"ImmunoScoreRoh"], "double")
    myoutput <- capture.output(immunoScoreSign(rmatrix, nametype = "SYMBOL", author = "Roh"))
    myoutput <- substring(myoutput[1], regexpr("g ", myoutput[1])+2, regexpr("of", myoutput[1])-3)
    expect_true(as.numeric(myoutput)>=0 & as.numeric(myoutput)<=100)
})


